
import back_end.Animal;
import back_end.DadosApp;
import back_end.Tutor;
import back_end.Vacina;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author T-GAMER
 */
public class Vacinar extends javax.swing.JFrame {
    
    private Tutor tutor;
    private Animal animal;
    private Vacina vacina;
    
    /**
     * Creates new form CadTutor
     */
    public Vacinar() {
        initComponents();
        setLocationRelativeTo(null);
   
    }
    
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TITULO = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomeAnimal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cpfTutor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        NomeVacina = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dataAplicacao = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dataVencimento = new javax.swing.JTextField();
        Registrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TITULO.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        TITULO.setText("Vacinar Animal");

        jLabel2.setText("Nome Animal:");

        jLabel3.setText("CPF Tutor:");

        jLabel4.setText("Vacina");

        jLabel5.setText("Data Aplic");

        dataAplicacao.setName(""); // NOI18N
        dataAplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataAplicacaoActionPerformed(evt);
            }
        });

        jLabel6.setText("Data Validade");

        Registrar.setText("Registrar");
        Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(nomeAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(cpfTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataVencimento)
                            .addComponent(dataAplicacao)
                            .addComponent(NomeVacina))))
                .addGap(140, 140, 140))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(TITULO))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(Registrar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(TITULO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomeAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cpfTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(NomeVacina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dataAplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(dataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(Registrar)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dataAplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataAplicacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataAplicacaoActionPerformed

   
    private void RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarActionPerformed
       
        
        for(Tutor tutor: DadosApp.clinica.getTutores()){
            if(tutor.getCpf().equalsIgnoreCase(cpfTutor.getText())){
                this.tutor = tutor;
               
                
            }
        }
        
        if(this.tutor == null){
            JOptionPane.showMessageDialog(this, "Nenhum tutor encontrado com esse CPF.");
            Utilitarios.limparCampos(List.of(nomeAnimal, cpfTutor, NomeVacina, dataAplicacao, dataVencimento));
            return;
        }
       
        
        
       
        
        for(Animal animal:this.tutor.getAnimais()){
            if(animal.getNome().equalsIgnoreCase(nomeAnimal.getText())){
                this.animal = animal;
                
                
            }
        }
        
        if(this.animal == null){
            JOptionPane.showMessageDialog(this, "Esse tutor não tem nenhum animal com esse nome!");
            Utilitarios.limparCampos(List.of(nomeAnimal, cpfTutor, NomeVacina, dataAplicacao, dataVencimento));
            return;
        }
        
        
        if(!DadosApp.clinica.vacinaExiste(NomeVacina.getText())){
            JOptionPane.showMessageDialog(this, "Vacina não existe no estoque!");
            Utilitarios.limparCampos(List.of(nomeAnimal, cpfTutor, NomeVacina, dataAplicacao, dataVencimento));
            return;
        }
        this.vacina = DadosApp.clinica.getVacina(NomeVacina.getText());
        
       
        this.animal.adicionarVacina(this.vacina, LocalDate.parse(dataAplicacao.getText()), LocalDate.parse(dataVencimento.getText()));
        
       String nomeVacina = this.vacina.getNome();
        double preco = this.vacina.getPreco();

        String mensagem = String.format(
            " Vacina \"%s\" aplicada com sucesso.\n Valor a ser pago: R$ %.2f",
            nomeVacina, preco
        );

        JOptionPane.showMessageDialog(this, mensagem, "Vacina Registrada", JOptionPane.INFORMATION_MESSAGE);

        
        this.dispose();

    }//GEN-LAST:event_RegistrarActionPerformed

    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadTutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadTutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadTutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadTutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadTutor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NomeVacina;
    private javax.swing.JButton Registrar;
    private javax.swing.JLabel TITULO;
    private javax.swing.JTextField cpfTutor;
    private javax.swing.JTextField dataAplicacao;
    private javax.swing.JTextField dataVencimento;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nomeAnimal;
    // End of variables declaration//GEN-END:variables
}
